<a href="https://colab.research.google.com/github/shuvookd/Bangalure_House_Price_Predection/blob/main/Bangalure_House_price_Predection(Linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load Library

In [58]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

### Read Dataset

In [59]:
df = pd.read_csv("/content/bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

### Split Data

In [60]:
X = df.drop('price', axis=1)
y = df['price']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


### Feature Scaling

In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

### Linear Regression

In [63]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [64]:
lr.coef_

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468905e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029424e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968545e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886278e-01,  8.03443207e-01,  2.99182164e+00,  3.86430413e-03,
        1.05037261e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -

In [65]:
lr.intercept_

95.0802729985955

### Predecting the Value of Home and Test

In [66]:
X_test[0, :]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [67]:
lr.predict([X_test[0, :]])

array([76.90661876])

In [68]:
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [69]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [70]:
linear_Regression_accuracy_score = lr.score(X_test, y_test)
linear_Regression_accuracy_score

0.790383709268225

### Model Evaluation

In [71]:
y_pred = lr.predict(X_test)
y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [72]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

### Mean Square Error(MSE), Root Mean Square Error(RMSE), Mean Absolute Error(MAE) for Linear Regression

In [73]:
mse = mean_squared_error(y_test, y_pred) 
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test,y_pred)

In [74]:
print('MSE for Linear Regression : ', mse)
print('RMSE for Linear Regression :', rmse)
print("MAE for Linear Regression :", mae)
print("Accuracy Score for Linear Regression :", linear_Regression_accuracy_score)

MSE for Linear Regression :  4211.806905823333
RMSE for Linear Regression : 64.8984353110561
MAE for Linear Regression : 19.091147376118794
Accuracy Score for Linear Regression : 0.790383709268225


### Implimenting Ridge & Lasso Regression

In [75]:
from sklearn.linear_model import Ridge,Lasso

Ridge

In [76]:
rd = Ridge()
rd.fit(X_train,y_train)
ridge_score = rd.score(X_test, y_test)

In [77]:
ridge_y_pred = rd.predict(X_test)
ridge_y_pred

array([ 76.92207759,  15.25945686, 113.70019676, ...,  21.29069552,
        71.42880399, 230.01781562])

Lasso

In [78]:
ls = Lasso()
ls.fit(X_train,y_train)
lasso_score = ls.score(X_test, y_test)

In [79]:
lasso_y_pred = ls.predict(X_test)
lasso_y_pred

array([ 81.3103182 ,  17.58271013, 132.5549385 , ...,  19.98593615,
        65.43686586, 224.75058885])

### Mean Square Error(MSE), Root Mean Square Error(RMSE), Mean Absolute Error(MAE) for Ridge

In [80]:
ridge_mse = mean_squared_error(y_test, ridge_y_pred) 
ridge_rmse = np.sqrt(mse)
ridge_mae = mean_absolute_error(y_test,ridge_y_pred)

In [81]:
print('MSE for Ridge : ', ridge_mse)
print('RMSE for Ridge : ', ridge_rmse)
print("MAE for Ridge : ", ridge_mae)
print("Accuracy Score for Ridge:", ridge_score)

MSE for Ridge :  4208.091155861566
RMSE for Ridge :  64.8984353110561
MAE for Ridge :  19.081757190374443
Accuracy Score for Ridge: 0.7905686374336628


### Mean Square Error(MSE), Root Mean Square Error(RMSE), Mean Absolute Error(MAE) for Lasso

In [82]:
lasso_mse = mean_squared_error(y_test, lasso_y_pred) 
lasso_rmse = np.sqrt(mse)
lasso_mae = mean_absolute_error(y_test,lasso_y_pred)

In [83]:
print('MSE for Lasso : ', lasso_mse)
print('RMSE for Lasso : ', lasso_rmse)
print("MAE for Lasso : ", lasso_mae)
print("Accuracy Score for Lasso:", lasso_score)

MSE for Lasso :  3945.5033362812906
RMSE for Lasso :  64.8984353110561
MAE for Lasso :  18.638846581863778
Accuracy Score for Lasso: 0.8036373003525774


### Comparision Between Linear Regression , Ridge & Lasso

In [84]:
print("Accuracy Score for Linear Regression :", linear_Regression_accuracy_score)
print("Accuracy Score for Ridge:", ridge_score)
print("Accuracy Score for Lasso:", lasso_score)

Accuracy Score for Linear Regression : 0.790383709268225
Accuracy Score for Ridge: 0.7905686374336628
Accuracy Score for Lasso: 0.8036373003525774


In [85]:
print("Accuracy Score for Lasso:", lasso_score)

Accuracy Score for Lasso: 0.8036373003525774
